### PR TITLE
Add checking input promptly

### PR DESCRIPTION
**Pull request by watilde**
I added checking input promptly for fixing https://github.com/npm/npm/issues/4700 and https://github.com/npm/npm/issues/5044.
See also related PR https://github.com/isaacs/promzard/pull/13

### CODE REVIEW

**Comment by iarna** [comment]
Thanks for this! I landed it as 487153d

**Comment by watilde** [comment]
@iarna Thanks! Actually, this PR has also depends on this PR: https://github.com/isaacs/promzard/pull/13

**Comment by iarna** [comment]
@watilde Hah, ok so I thought I'd tested this and seen it work without that PR. And indeed it does. The reason is that Isaac landed:

https://github.com/isaacs/promzard/pull/10

Which makes `er.notValid` trigger the loop instead of `er.again`.

So the version I merged has an extra property on its error object, but otherwise is fine.

**Comment by michaelnisi** [comment]
You might want to add a test. Take a look at the tests I've recently added for name validation https://github.com/npm/init-package-json/blob/master/test/name-uppercase.js and https://github.com/npm/init-package-json/blob/master/test/name-spaces.js

**Pull request closed without merging**
