### PR TITLE
Feat : tests to run on Github Actions (#114)

### PR DESCRIPTION
**Pull request by mohitmishra786**

### CODE REVIEW

**Comment by wraithgar** [comment]
We are going to be implementing this kind of stuff on the repos that are a part of the cli, but doing it internally using https://github.com/npm/template-oss.

**Comment by mohitmishra786** [comment]
> We are going to be implementing this kind of stuff on the repos that are a part of the cli, but doing it internally using https://github.com/npm/template-oss.


i didn't got your point, can you please elaborate a little it will help me to understand you

**Comment by wraithgar** [comment]
This pr shows it in action https://github.com/npm/are-we-there-yet/pull/111

It is something we are going to use to get our repos synced as far as CI, linting, etc.  It is also something we are going to do ourselves.  Much like the updating of dependencies in a given repo, this is one of those things we would prefer to do ourselves.  Feel free to make code PRs still.

**Comment by mohitmishra786** [comment]
ok i got your point

**Pull request closed without merging**
