### PR TITLE
Configurable entry point with config::init.main

### PR DESCRIPTION
**Pull request by WORMSS**
I am afraid I am not sure how to make the test scripts work "as is" **and** with a configurable main parameter, so I only did the change to **default-input.js** :sob:. Hopefully this will be enough.

### CODE REVIEW

**Comment by othiym23** [comment]
This would be great with a test, but we'll make it happen ourselves (eventually) if you don't get to it first.

**Comment by iarna** [comment]
Given current priorities, we are unlikely to get to writing a test for this ourselves for this in the foreseeable future, so if you would like to see this landed you'll need to write the test yourself.

**Comment by michaelnisi** [comment]
What are those double `config.get`calls about? I can't remember.

**Comment by michaelnisi** [comment]
OK, made it more readable #58

**Comment by WORMSS** [comment]
Those double names were because I seen in other parts of the system that it looked for either a - (hyphen) or a . (dot). So that is why it looks for both.

**Comment by WORMSS** [comment]
For me root is where I put all the manifest.js .editorconfig .gitignores .project .otherstuff settings.. and then `app/` folder is where all the files for the project go. so I **always** have to re-write the main manually. Everything else is enter, enter, enter, enter

**Comment by iarna** [comment]
Thanks for your work on this. I'm closing this as it hasn't seen any activity in a year. Please feel free to re-PR (w/tests) if you'd still like to see this change land.

**Pull request closed without merging**
